M48
; DRILL file {KiCad 8.0.6} date 2025-02-14T11:57:29-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-02-14T11:57:29-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1280
%
G90
G05
T1
X5.7283Y-4.6654
T2
X6.0236Y-4.6654
M30
