M48
; DRILL file {KiCad 8.0.6} date 2025-01-14T14:57:27-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-01-14T14:57:27-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.6
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ViaDrill
T1C0.0118
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0433
%
G90
G05
T1
X4.9213Y-3.563
X4.9606Y-3.563
T2
X4.8Y-3.5
X4.8Y-3.6
X4.8Y-3.7
X4.8Y-3.8
X5.3Y-3.5
X5.3Y-3.6
X5.3Y-3.7
X5.3Y-3.8
X5.3Y-3.9
M30
